'use server'
import { toJson } from "@/lib/utils";
import { z } from 'zod'
import { createServerSupabaseClient } from '@/src/lib/supabase'
import { getBenefitsWorkspace } from '@/src/services/benefitsService'
import type { ActionResponse } from './types'
import { actionFailure, actionSuccess } from './types'
import { dateSchema, requireOrganizationContext, revalidateWorkspacePaths, uuidSchema, validationFailure } from './_shared'
const planSchema=z.object({name:z.string().min(2).max(240),provider:z.string().max(160).optional().nullable(),planType:z.string().min(2).max(120),description:z.string().max(6000).optional().nullable(),employeeCost:z.number().nonnegative().default(0),employerCost:z.number().nonnegative().default(0),currencyCode:z.string().length(3).default('USD'),enrollmentStart:dateSchema.optional().nullable(),enrollmentEnd:dateSchema.optional().nullable()})
const enrollSchema=z.object({planId:uuidSchema,employeeId:uuidSchema,effectiveDate:dateSchema.optional().nullable(),status:z.enum(['pending','enrolled','waived','cancelled']).default('enrolled'),coverage:z.record(z.string(),z.unknown()).default({})})
export async function getBenefitsOverviewAction():Promise<ActionResponse<any>>{const auth=await requireOrganizationContext('employee');if(!auth.success)return auth;try{const supabase=await createServerSupabaseClient();const [workspace,employees]=await Promise.all([getBenefitsWorkspace(supabase,auth.data.organizationId),supabase.from('employees').select('id,first_name,last_name,employee_number,status').eq('organization_id',auth.data.organizationId).is('deleted_at',null)]);if(employees.error)return actionFailure(employees.error.message);return actionSuccess({...workspace,employees:employees.data||[]})}catch(e){return actionFailure(e instanceof Error?e.message:'Unable to load benefits.')}}
export async function createBenefitPlanAction(input:z.input<typeof planSchema>):Promise<ActionResponse<any>>{const parsed=planSchema.safeParse(input);if(!parsed.success)return validationFailure(parsed.error);const auth=await requireOrganizationContext('admin');if(!auth.success)return auth;try{const s=await createServerSupabaseClient();const {data,error}=await s.from('benefit_plans').insert({organization_id:auth.data.organizationId,name:parsed.data.name,provider:parsed.data.provider||null,plan_type:parsed.data.planType,description:parsed.data.description||null,employee_cost:parsed.data.employeeCost,employer_cost:parsed.data.employerCost,currency_code:parsed.data.currencyCode,enrollment_start:parsed.data.enrollmentStart||null,enrollment_end:parsed.data.enrollmentEnd||null,status:'active'}).select().single();if(error||!data)return actionFailure(error?.message||'Benefit plan creation failed.');await s.from('audit_logs').insert({organization_id:auth.data.organizationId,actor_user_id:auth.data.userId,action:'create',entity_type:'benefit_plan',entity_id:data.id,before_state:null,after_state:{name:data.name}});revalidateWorkspacePaths('/','/benefits');return actionSuccess(data)}catch(e){return actionFailure(e instanceof Error?e.message:'Unable to create benefit plan.')}}
export async function enrollBenefitAction(input:z.input<typeof enrollSchema>):Promise<ActionResponse<any>>{const parsed=enrollSchema.safeParse(input);if(!parsed.success)return validationFailure(parsed.error);const auth=await requireOrganizationContext('admin');if(!auth.success)return auth;try{const s=await createServerSupabaseClient();const [plan,employee]=await Promise.all([s.from('benefit_plans').select('id').eq('id',parsed.data.planId).eq('organization_id',auth.data.organizationId).maybeSingle(),s.from('employees').select('id').eq('id',parsed.data.employeeId).eq('organization_id',auth.data.organizationId).is('deleted_at',null).maybeSingle()]);if(plan.error||!plan.data)return actionFailure(plan.error?.message||'Plan not found.');if(employee.error||!employee.data)return actionFailure(employee.error?.message||'Employee not found.');const {data,error}=await s.from('benefit_enrollments').upsert({organization_id:auth.data.organizationId,benefit_plan_id:parsed.data.planId,employee_id:parsed.data.employeeId,status:parsed.data.status,effective_date:parsed.data.effectiveDate||null,selected_coverage:toJson(parsed.data.coverage)},{onConflict:'benefit_plan_id,employee_id'}).select().single();if(error||!data)return actionFailure(error?.message||'Benefit enrollment failed.');await s.from('audit_logs').insert({organization_id:auth.data.organizationId,actor_user_id:auth.data.userId,action:'update',entity_type:'benefit_enrollment',entity_id:data.id,before_state:null,after_state:{plan_id:parsed.data.planId,employee_id:parsed.data.employeeId,status:data.status}});revalidateWorkspacePaths('/','/benefits');return actionSuccess(data)}catch(e){return actionFailure(e instanceof Error?e.message:'Unable to enroll benefit.')}}
