'use server'
import { z } from 'zod'
import { createServerSupabaseClient } from '@/src/lib/supabase'
import { getEquityWorkspace } from '@/src/services/equityService'
import type { ActionResponse } from './types'
import { actionFailure, actionSuccess } from './types'
import { dateSchema, requireOrganizationContext, revalidateWorkspacePaths, uuidSchema, validationFailure } from './_shared'
const grantSchema=z.object({employeeId:uuidSchema,grantType:z.enum(['option','rsu','share','phantom']),grantDate:dateSchema,quantity:z.number().positive(),strikePrice:z.number().nonnegative().optional().nullable(),currencyCode:z.string().length(3).default('USD'),vestingStartDate:dateSchema,vestingMonths:z.number().int().min(1).max(240).default(48),cliffMonths:z.number().int().min(0).max(120).default(0)})
export async function getEquityOverviewAction():Promise<ActionResponse<any>>{const auth=await requireOrganizationContext('employee');if(!auth.success)return auth;try{const s=await createServerSupabaseClient();const [workspace,employees]=await Promise.all([getEquityWorkspace(s,auth.data.organizationId),s.from('employees').select('id,first_name,last_name,employee_number,status').eq('organization_id',auth.data.organizationId).is('deleted_at',null)]);if(employees.error)return actionFailure(employees.error.message);return actionSuccess({...workspace,employees:employees.data||[]})}catch(e){return actionFailure(e instanceof Error?e.message:'Unable to load equity.')}}
export async function createEquityGrantAction(input:z.input<typeof grantSchema>):Promise<ActionResponse<any>>{const parsed=grantSchema.safeParse(input);if(!parsed.success)return validationFailure(parsed.error);const auth=await requireOrganizationContext('admin');if(!auth.success)return auth;try{const s=await createServerSupabaseClient();const {data:employee,error:employeeError}=await s.from('employees').select('id').eq('id',parsed.data.employeeId).eq('organization_id',auth.data.organizationId).is('deleted_at',null).maybeSingle();if(employeeError||!employee)return actionFailure(employeeError?.message||'Employee not found.');const months=parsed.data.vestingMonths;const end=new Date(`${parsed.data.vestingStartDate}T12:00:00Z`);end.setUTCMonth(end.getUTCMonth()+months);const {data,error}=await s.from('equity_grants').insert({organization_id:auth.data.organizationId,employee_id:parsed.data.employeeId,grant_type:parsed.data.grantType,grant_date:parsed.data.grantDate,quantity:parsed.data.quantity,strike_price:parsed.data.strikePrice??null,currency_code:parsed.data.currencyCode,vesting_start_date:parsed.data.vestingStartDate,vesting_end_date:end.toISOString().slice(0,10),cliff_months:parsed.data.cliffMonths,vesting_months:months,status:'active'}).select().single();if(error||!data)return actionFailure(error?.message||'Grant creation failed.');const events=Array.from({length:months},(_,i)=>{const d=new Date(`${parsed.data.vestingStartDate}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+i+1);return {organization_id:auth.data.organizationId,equity_grant_id:data.id,vesting_date:d.toISOString().slice(0,10),quantity:Number((parsed.data.quantity/months).toFixed(4)),status:i+1<=parsed.data.cliffMonths?'scheduled':'scheduled'}});const {error:eventError}=await s.from('equity_vesting_events').insert(events);if(eventError)return actionFailure(`Grant created but vesting schedule failed: ${eventError.message}`);await s.from('audit_logs').insert({organization_id:auth.data.organizationId,actor_user_id:auth.data.userId,action:'create',entity_type:'equity_grant',entity_id:data.id,before_state:null,after_state:{employee_id:parsed.data.employeeId,quantity:parsed.data.quantity,grant_type:parsed.data.grantType}});revalidateWorkspacePaths('/','/equity');return actionSuccess(data)}catch(e){return actionFailure(e instanceof Error?e.message:'Unable to create equity grant.')}}
