-- Fluxentiq enterprise tenant/RBAC/SSO extension.
CREATE TABLE IF NOT EXISTS public.sso_configurations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,provider TEXT NOT NULL,issuer_url TEXT,client_id TEXT,metadata_url TEXT,enabled BOOLEAN NOT NULL DEFAULT FALSE,created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(organization_id,provider));
CREATE TABLE IF NOT EXISTS public.organization_domain_whitelists (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,domain CITEXT NOT NULL,verified_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(organization_id,domain));
CREATE TABLE IF NOT EXISTS public.ip_restrictions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,cidr CIDR NOT NULL,label TEXT,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.webhook_endpoints (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,name TEXT NOT NULL,url TEXT NOT NULL,event_types JSONB NOT NULL DEFAULT '[]'::jsonb,secret_hash TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN('active','disabled')),created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE public.sso_configurations ENABLE ROW LEVEL SECURITY;ALTER TABLE public.organization_domain_whitelists ENABLE ROW LEVEL SECURITY;ALTER TABLE public.ip_restrictions ENABLE ROW LEVEL SECURITY;ALTER TABLE public.webhook_endpoints ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.sso_configurations FOR ALL USING(public.is_organization_member(organization_id)) WITH CHECK(public.is_organization_member(organization_id));
CREATE POLICY tenant_isolation ON public.organization_domain_whitelists FOR ALL USING(public.is_organization_member(organization_id)) WITH CHECK(public.is_organization_member(organization_id));
CREATE POLICY tenant_isolation ON public.ip_restrictions FOR ALL USING(public.is_organization_member(organization_id)) WITH CHECK(public.is_organization_member(organization_id));
CREATE POLICY tenant_isolation ON public.webhook_endpoints FOR ALL USING(public.is_organization_member(organization_id)) WITH CHECK(public.is_organization_member(organization_id));
